import { useState } from 'react'

import { services, professionals } from './features/booking.js'
import Booking from './features/Booking.jsx'

function Artwork({ small = false }) {
  return <div className={small ? 'artwork artwork-small' : 'artwork'} aria-label="Composición decorativa en tonos rosados y beige"><div className="art-orbit" /><div className="art-arch"><div className="art-vase" /><div className="art-stem stem-one" /><div className="art-stem stem-two" /><div className="art-stem stem-three" /></div><div className="art-pedestal" /><span className="art-spark">✧</span></div>
}

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <>
    <div className="announcement">Un ratito para ti. Un espacio para florecer. <span>✧</span></div>
    <header className="header"><a className="logo" href="#inicio" aria-label="Mussas, inicio">mussas<span>BEAUTY STUDIO</span></a><button className="menu-toggle" aria-label={menuOpen ? 'Cerrar menú' : 'Abrir menú'} aria-expanded={menuOpen} aria-controls="navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? 'Cerrar ✕' : 'Menú ☰'}</button><nav id="navigation" className={menuOpen ? 'navigation open' : 'navigation'} onClick={() => setMenuOpen(false)}><a href="#servicios">Servicios</a><a href="#nosotras">Nuestro espacio</a><a href="#galeria">Galería</a><a className="button button-small" href="#reservas">Agenda tu visita <span>↗</span></a></nav></header>
    <main>
      <section id="inicio" className="hero section-wrap"><div className="hero-copy"><p className="eyebrow"><span /> BELLEZA QUE NACE DE TI</p><h1>Tu esencia.<br />Tu belleza.<br /><em>Tu momento.</em></h1><p className="hero-description">Un espacio para desconectar, cuidarte y reencontrarte con tu mejor versión. Bienvenida a Mussas.</p><div className="hero-actions"><a className="button" href="#reservas">Agenda tu momento <span>↗</span></a><a className="text-link" href="#nosotras">Conócenos <span>→</span></a></div><div className="hero-note"><span className="note-icon">✧</span><span>Hecho con dedicación.<br /><strong>Pensado para ti.</strong></span></div></div><div className="hero-visual"><Artwork /><div className="visual-label"><span>EL ARTE DE CUIDARTE</span><span>mussas — beauty studio</span></div><div className="floating-note">Un poquito de calma,<br /><em>mucho amor propio.</em></div></div></section>
      <div className="ribbon"><span>BELLEZA CON INTENCIÓN</span><i>✧</i><span>TIEMPO PARA TI</span><i>✧</i><span>DETALLES QUE ENAMORAN</span><i>✧</i><span>SIEMPRE TÚ</span></div>
      <section id="servicios" className="services section-wrap"><div className="section-heading"><div><p className="eyebrow">ELIGE TU MOMENTO</p><h2>Pequeños rituales.<br /><em>Grandes sensaciones.</em></h2></div><p>Deja el día a día afuera.<br />Aquí, la protagonista eres tú.</p></div><div className="service-grid">{services.map(service => <article className="service-card" key={service.number}><div className="card-top"><span>{service.number}</span><span className="service-icon">{service.icon}</span></div><p className="service-tag">{service.tag}</p><h3>{service.title}</h3><p>{service.description}</p><a href="#reservas" className="service-link">Me interesa <span>↗</span></a></article>)}</div></section>
      <section id="nosotras" className="about section-wrap"><div className="about-art"><Artwork small /><div className="about-caption">Aquí florece tu belleza.</div></div><div className="about-copy"><p className="eyebrow">MUCHO MÁS QUE UN SALÓN</p><h2>Un espacio bonito.<br /><em>Una experiencia tuya.</em></h2><p>Creemos en esa belleza que te hace sentir bien. En escuchar, cuidar los detalles y dedicarte el tiempo que mereces.</p><p>Mussas nace para ser ese pequeño respiro en tu rutina: un lugar cálido donde puedes ser tú, relajarte y dejarte cuidar.</p><div className="about-values"><span>✧ Atención cercana</span><span>✧ Cuidado en cada detalle</span></div></div></section>
      <section id="galeria" className="gallery section-wrap"><div className="section-heading"><div><p className="eyebrow">EL UNIVERSO MUSSAS</p><h2>Detalles para <em>inspirarte.</em></h2></div><span className="gallery-coming">Nuestra galería, muy pronto ↗</span></div><div className="gallery-grid"><div className="gallery-tile tile-one"><span className="tile-art">✧</span><span>Tu próximo cambio</span></div><div className="gallery-tile tile-two"><span className="tile-art">♡</span><span>Pequeños detalles</span></div><div className="gallery-tile tile-three"><span className="tile-art">✺</span><span>Momentos Mussas</span></div></div></section>
      <Booking />
      <section id="contacto" className="contact"><p className="eyebrow">TE ESPERAMOS EN MUSSAS</p><h2>Un ratito <em>para ti.</em></h2><p>Llico 1089, San Miguel.<br />Lunes a viernes: 11:00 – 19:00 hrs · Sábado: 11:00 – 17:00 hrs</p><div className="contact-links">{professionals.map(person => <a key={person.id} className="button" href={'https://wa.me/' + person.phone} target="_blank" rel="noopener noreferrer">WhatsApp {person.name}<small>{person.displayPhone}</small></a>)}</div><a className="instagram-link" href="https://www.instagram.com/mussasstudio/" target="_blank" rel="noopener noreferrer">Instagram · @mussasstudio ↗</a><span className="contact-star" aria-hidden="true">✧</span></section>
    </main>
    <footer className="footer section-wrap"><a className="logo" href="#inicio">mussas<span>BEAUTY STUDIO</span></a><p>Belleza, calma y un momento para ti.</p><a className="text-link" href="#inicio">Volver arriba ↑</a><div className="footer-bottom"><span>© {new Date().getFullYear()} Mussas. Todos los derechos reservados.</span><span>Hecho con amor y buenos detalles ✧</span></div></footer>
  </>
}
